### PR TITLE
Invalid UTF-8 character fix

### PR DESCRIPTION
**Pull request by gorbit99**
This fixes an issue with non-utf-8 character streams returning an error. This happens often, if you have text containing characters from the extended ascii range. This pr fixes that by implementing a new BufRead that reads strings using from_utf8_lossy.
This shouldn't affect performance, although a much faster solution could be achieved by manually ignoring all actual byte values and only looking at the utf-8 codes.

A code formatting might need to be applied, as there was no rustfmt config inside the repo.

### CODE REVIEW

**Comment by wfxr** [comment]
@gorbit99 Sorry for the late reply! Can you provide a minimal file with `utf-8` encoding which causes the error?

**Comment by gorbit99** [comment]
[test.txt](https://github.com/wfxr/code-minimap/files/6438823/test.txt)
The issue arises, when the file isn't valid utf-8, this mainly happens when the file was created on windows and brought over to linux with characters from the extended ascii range.
This exact example was generated by doing `printf "\xff` > test.txt

**Comment by wfxr** [comment]
Should this file be considered a legal utf-8 file?

```
$ printf "\xff" > test.txt

$ file -i test.txt
test.txt: application/octet-stream; charset=binary
```

```
$ echo hello > test.txt

$ file -i test.txt # ascii is subset of utf-8
test.txt: text/plain; charset=us-ascii

$ printf "\xff" >> test.txt

$ file -i test.txt # iso-8859-1 (not utf-8 ?)
test.txt: text/plain; charset=iso-8859-1
```

One problem I considered is that if we support non `utf-8` charsets through lossy conversion, all character sets that are not originally supported will no longer report an error, but will silently produce an incorrect result.

**Comment by gorbit99** [comment]
The other option is to load in the file encoding, compare it to a table, parse it accordingly and spit out results that way, which is more complex, definitely not cross platform and probably a whole lot slower. And imo having the results be mostly correct is preferable over not supporting ascii files at all.

**Comment by wfxr** [comment]
> And imo having the results be mostly correct is preferable over not supporting ascii files at all.

@gorbit99 Make sense. I did some refactors based on your work. You can review it, and give me feedback if there is something wrong.

**Comment by gorbit99** [comment]
Seems fine to me.

**Comment by wfxr** [comment]
@gorbit99 Merged. Thanks for your contribution!

**Pull request merged**
